### ISSUE TITLE
channel list?

### ISSUE THREAD

**Issue by crackers8199** [AngellusMortis/sxm-player#13]
the documentation for this thing is so horrific...is there an actual channel list anywhere? would be nice to use VLC to just grab by channel number, but that doesn't seem to work.

**Comment by parkerlreed** [comment]
Right here? https://sxm-client.readthedocs.io/en/latest/usage.html#sxm-channels

**Comment by crackers8199** [comment]
ah, sxm-client. that explains how i missed it, since sxm-client isn't mentioned anywhere in the sxm-player github or docs.

thanks.
