### ISSUE TITLE
Auth Failing

### ISSUE THREAD

**Issue by jfarre20** [AngellusMortis/sxm-player#14]
Operating System: Docker
Image: angellusmortis/sxm-player:latest

### Description

Stopped working overnight, noticed I see 

`<TITLE>Access Denied</TITLE> </HEAD><BODY> <H1>Access Denied</H1> You don't have permission to access "http://player.siriusxm.com/rest/v2/experience/modules/modify/authentication" on this server.<P> Reference #18.4d680117.1702569197.dc2276d </BODY> </HTML>`

In the logs.

Seems like they changed auth again?

I can still log in via the web

**Comment by PeebsATX** [comment]
Yeap same issue here, ironic I just got it working a few days ago and here we are.

**Comment by jmperagine** [comment]
Was working for the past 2 years, now getting:  "ERROR Unable to authenticate because login failed"
I should note, using with Mo0de Audio on a Raspberry Pi4B, actually, 2 of them.
Credentials work on Chrome, Edge, and Android app.

**Comment by PeebsATX** [comment]
https://www.reddit.com/r/siriusxm/s/hOpuCRhmEL

Seems likely that same change was the reason

**Comment by jmperagine** [comment]
...and, it's working. all good.

**Comment by asingletary** [comment]
hah, you're right it is working again...

**Comment by jfarre20** [comment]
it started working..
